import { Router } from 'express';
import productController from '../controllers/productController.js';
import auth, { verifyAdmin } from '../middleware/auth.js';
import userController from '../controllers/userController.js';
import CategoryModel from '../models/categoriesModel.js';
import CategoryController from '../controllers/categoryController.js';
import AddressController from '../controllers/addressController.js';
import CheckoutController from '../controllers/walletController.js';
import PricingController from '../controllers/priceController.js';
import RentalController from '../controllers/rentalController.js';
import ReviewController from '../controllers/reviewController.js';
import WishListController from '../controllers/wishlistController.js';
import ChatController from '../controllers/chatController.js';
import AdminController from '../controllers/dashboardController.js';


const userRouter = Router();

userRouter.post('/login', userController.login);
userRouter.post('/register', userController.register);
userRouter.get('/products', productController.getAllProducts);
userRouter.get('/category-fields/:id', productController.getCategoryFields);
userRouter.get('/categories', CategoryController.getAllCategories);
userRouter.get('/user-addresses', auth, AddressController.getUserAddresses);
userRouter.post('/add-address', auth, AddressController.createAddress);
userRouter.put('/update-address/:id', auth, AddressController.updateAddress);
userRouter.delete('/delete-address/:id', auth, AddressController.deleteAddress);
userRouter.post('/add-product', auth, productController.postProduct);
userRouter.get('/checkout-info', auth, CheckoutController.getCheckoutPageData);
userRouter.get('/tier-pricing', PricingController.getPriceByProduct);
userRouter.get('/products/:id', productController.getProductDetail);
userRouter.post('/booked-dates', RentalController.getBookedDates);
userRouter.post('/create-order', auth, RentalController.createOrder);
userRouter.get('/rental/detail/:id', auth, RentalController.getOrderDetailById);
userRouter.post('/cancel-order',auth, RentalController.cancelOrder);
userRouter.post('/status-order',auth, RentalController.getOwnerStats);
userRouter.post('/rental/approve-request', auth, RentalController.approveRequest);
userRouter.post('/rental/reject-request', auth, RentalController.rejectRequest); 
userRouter.get('/rental/my-orders', auth, RentalController.fetchMyOrders);   
userRouter.post('/rental/renter-return',auth, RentalController.renterReturnOrder);
userRouter.post('/rental/report-damage',auth, RentalController.reportDamage);
userRouter.get('/rental/policy/:productId', RentalController.getProductPolicies);
userRouter.get('/rental/report-damage/:rentalRequestId', auth, RentalController.getDamageReport);
userRouter.post('/rental/accept-report/:rentalRequestId', auth, RentalController.acceptDamageReport);
userRouter.post('/products/filter', productController.getProductsFilter);
userRouter.get('/my-products', auth, productController.getMyProducts);
userRouter.post('/upload-image-avatar', auth,userController.uploadAvatar);
userRouter.put("/update-profile", auth, userController.updateProfile);
userRouter.post('/changePassword',auth, userController.changePassword);
userRouter.post('/review/add',auth, ReviewController.addReview);
userRouter.post('/toggle', auth, WishListController.toggleWishlist);
userRouter.get('/get-wishlist', auth, WishListController.getWishlist);
userRouter.get('/checkout-data',auth , CheckoutController.getCheckoutPageData);
userRouter.get('/wallet', auth, CheckoutController.getWallet);
userRouter.post('/deposit', auth, CheckoutController.depositMoney);
userRouter.post('/confirm-payment', userRouter, CheckoutController.confirmPayment);
userRouter.get('/shop-products/:shopId', productController.getShopProducts);
userRouter.get('/my-products-manager', auth, productController.getMyProductStatus);
userRouter.patch('/toggle-status', auth, productController.toggleStatus);
userRouter.post('/chat/get-or-create', auth , ChatController.getOrCreateConversation);
userRouter.post('/upload-image', auth, ChatController.uploadChatImage);
userRouter.get('/my-conversations', auth, ChatController.getConversations);

userRouter.get('/products-admin', auth, verifyAdmin, productController.getProducts);
userRouter.post('/products/approve-admin',auth, verifyAdmin, productController.approveProduct);
userRouter.get('/users',auth, verifyAdmin, userController.getAllUsers);
userRouter.patch('/users/status',auth, verifyAdmin, userController.changeUserStatus);
userRouter.get('/admin/dashboard',auth, verifyAdmin, AdminController.getDashboardData);
userRouter.get('/dashboard/top-categories',auth, verifyAdmin, AdminController.getTopCategories);
userRouter.get('/admin/orders', auth,verifyAdmin, AdminController.getAllOrders);
export default userRouter;